### ISSUE TITLE
`any` Path Component only Matches a Single Character

### ISSUE THREAD

**Issue by calebkleveter** [vapor/routing#42]
The `any` component only matches a single character, so `v`, `1`, `*`, `c`, and anything else 1 character long will work, but `v1` gets a 404.

For example, if I have a route:

```swift
router.get("hello", any, "world") {req in //... }
```

This path matches:

```
/hello/o/world
```

But this doesn't match:

```
/hello/oo/world
```

**Comment by tanner0101** [comment]
Failing test case would be appreciated if possible. @proggeramlug you said you'd take a look? If not, I can.

**Comment by proggeramlug** [comment]
@tanner0101 I will by tomorrow! Unless your bored right now ;)

**Comment by proggeramlug** [comment]
@calebkleveter @tanner0101 

The specific project in which this case happened had the following routes structure:
```
router.grouped("v1")....
router.get(any, "health")
```

so the following routes did work:
```
/v1/whatever (goes into the group)
/whatever/health (goes to the health-get)
```

What did not work was:
`/v1/health `
The problem was that the "v1" is parsed before the "any" and so the "health" is never reached, though the group in v1 may not have a matching route.

The fix is really just for the app, to replace _v1_ in the group with _any_. After I did that it worked as expected.

I don't think we need any fixes for the module here but we may want to write something in the docs about it, in which order things are parsed.
