### ISSUE TITLE
warn if mis-match dynamic node registered

### ISSUE THREAD

**Issue by grosch** [vapor/routing#45]
Per @tanner0101 request I'm creating an issue that this seeming valid looking code doesn't work:

```swift
    func boot(router: Router) {
        router.get(Order.parameter, "edit", use: editViewHandler)
        router.get(Order.ID.parameter, "delete", use: deleteViewHandler)
    }
```

When trying to call delete and pull out an `Order.ID.parameter` you get an error about `int != order`

**Comment by tanner0101** [comment]
This is a limitation of the design of the router. A given node can have _at most_ one wildcard child. In the above example, there is no way to distinguish between an `Order` and `Order.ID` component. 

Since the `Order `component is registered first, the router node is set as `"order"` type. When the second route is registered, the router sees a [`parameter`](https://github.com/vapor/routing/blob/master/Sources/Routing/Register/PathComponent.swift#L7-L8) path component is already there and uses that. There is no check as to whether the existing parameter type is the same. 

A suggestion could be printing a warning (and perhaps failing) if non-matching `paramater` type path components are registered to the same node. This could be done [here](https://github.com/vapor/routing/blob/master/Sources/Routing/Routing/RouterNode.swift#L51-L65).

**Comment by JovanMilenkovic** [comment]
I wanted to open an issue for discussion similar to this so might as well do it here. I wanted to recommend that upon registering a new route, router issues a fatal error in case it concludes there is an ambiguity. Router has no way of making a valid decision on what should be done, and this happened because of a programmer error which I think should crash on boot.

**Comment by tanner0101** [comment]
This should be possible by adding a check that, if a dynamic child node already exists, its value is equal to the new dynamic node's value.
