### ISSUE TITLE
Only first route registration works

### ISSUE THREAD

**Issue by Sorix** [vapor/routing#48]
### Steps to reproduce

I've created fresh test repository: https://github.com/Sorix/RouterIssue

We have[ 2 paths](https://github.com/Sorix/RouterIssue/blob/f510c979f9c99a8ffa02f8b208f22a66006039db/Sources/App/routes.swift#L8-L12):

```swift
let testPath = router.grouped("test")

// /test/:string
testPath.get(String.parameter, use: testController.string)

// /test/:int/secondComponent
testPath.get(Int.parameter, "secondComponent", use: testController.int)
```

Let's try to call second route: 
```bash
curl "http://localhost:8080/test/12/secondComponent/"
```

### Expected behavior

Vapor will correctly route and call `testController.int`.

### Actual behavior

Vapor always calls firstly registered route (`controller.string`). That's why we get the error:
```bash
$ curl "http://localhost:8080/test/12/secondComponent/"
{"error":true,"reason":"Invalid parameter type: int != string"}
```

If we switch registrations, another route will work, but both will never work.

I don't think that my issue is relevant to #45 because I use different count of pathComponents.

### Environment

* Vapor Framework version: 3.1.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14

**Comment by twof** [comment]
It looks like in TrieRouter.swift:84 no attempt is make to ensure that the parameter in the current request is of the type listed in the registered route. Instead if the `Parameter` is in the correct position in a route path, it's matched regardless.

```swift
// no constants matched, check for dynamic members
if let parameter = currentNode.parameter {
    // if no constant routes were found that match the path, but
    // a dynamic parameter child was found, we can use it
    let value = ParameterValue(
        slug: String(data: parameter.value, encoding: .utf8) ?? "",
        value: path.routerParameterValue
    )
    parameters.values.append(value)
    currentNode = parameter
    continue search
}
```

Because of this, `value` could end up something like `ParameterValue(slug: "int", value: "hello")` and the request will still hit the correct responder.

Then everything falls apart when the user tries to do

```swift
let param = try req.parameters.next(String.self)
```

within their responder because the `Parameter` they're trying to retrieve has "int" as a slug

**Comment by calebkleveter** [comment]
This issue has been reported before: https://github.com/vapor/http/issues/206

The TLDR is that for the TrieRouter to handle types like this, you get a performance hit that would cause a lot of apps to be slower for a feature they don't even use. But if there is a good way for the router to solve the ambiguity, then a PR or issue outlining how to do that is welcome.

**Comment by Sorix** [comment]
@calebkleveter but here we have different number of parameters, I don't think that counting number of parameters will do a performance hit.

**Comment by calebkleveter** [comment]
It's true that that would probably be easier to implement that in a performant fashion, but I'm not sure that would be the correct solution because that only fixes half the problem (from my perspective).

The reason I say that is because if someone creates routes like you did, with different static route components, everything would work fine:

```
/:int
/:string/parameter
```

But if the routes are only dynamic (I get rid of the static parameter), it breaks as you explained when you opened this issue:

```
/:int
/:string
```

This would be unexpected behavior from the user's point of view, and so, a bug.

**Comment by twof** [comment]
Isn't it better to fix 1/2 a bug than no bugs?

**Comment by tanner0101** [comment]
+1 to what @calebkleveter said. 

This is definitely an implementation detail of the TrieRouter, but I think this limitation _does_ make some sense even at a higher level. At least in RESTful route design, having `/:int/foo` an `/:string` seems like an anti-pattern. For example, you'd usually have something like this:

```
GET /users/:id # gets a user
GET /users/:id/posts # gets a user's posts
```

Here `:id` should of course be the same type. RESTful routes (and usually routes in general) are hierarchical. 

So, if anything, I would think we should make registering conflicting route hierarchies a more obvious error.

**Comment by tanner0101** [comment]
I don't think the additional complexity or performance cost required to allow for multiple dynamic children per node would be worth it. This problem seems better solved by the higher level APIs for registering route handlers in Vapor. 

See https://forums.swift.org/t/named-routing-parameters/19434 for more discussion about a proposed improvement to these APIs.
